# -*- coding: utf-8 -*-
"""popularity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wG2e5HeGdd-TSz5E2EReH_pA0FBfgFUK
"""

# --------------------------------------
# 🎵 Spotify AI Recommender - Optimized Version with PCA for Cosine Similarity
# --------------------------------------

# 📦 Imports
import streamlit as st
import pandas as pd
import numpy as np
import json
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, f1_score, roc_auc_score, roc_curve
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

# 🛠️ Streamlit App Config
st.set_page_config(page_title="🎵 Spotify AI Recommender", layout="wide")

# --------------------------------------
# 🗅️ Load Data
# --------------------------------------
@st.cache_data(show_spinner=True)
def load_data():
    df = pd.read_csv("spotify_tracks.csv", low_memory=False)
    df = df.drop_duplicates(subset=['track_name', 'track_genre'], keep='first')
    audio_cols = ['danceability', 'energy', 'loudness', 'speechiness', 'acousticness',
                  'instrumentalness', 'liveness', 'tempo', 'duration_ms', 'valence']
    df[audio_cols] = df[audio_cols].fillna(df[audio_cols].mean()).astype(np.float32)
    return df, audio_cols

# 📊 Load and prepare data
spotify_df, model_features = load_data()
X_valence = spotify_df[model_features[:-1]]
y_valence = (spotify_df['valence'] > 0.5).astype(int)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_valence)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_valence, test_size=0.2, random_state=42)

# --------------------------------------
# 🔍 Sidebar Navigation
# --------------------------------------
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", [
    "EDA Dashboard", 
    "Model Evaluation", 
    "ML-Based Recommendation", 
    "Cosine Similarity Recommendation"
])

# --------------------------------------
# 📊 EDA Dashboard
# --------------------------------------
if page == "EDA Dashboard":
    st.title("📊 Spotify Dataset - EDA Dashboard")
    st.write(f"**Total Records:** {spotify_df.shape[0]:,}")
    st.dataframe(spotify_df[model_features].describe(), use_container_width=True)

    st.subheader("🎷 Genre Distribution (Top 20)")
    st.bar_chart(spotify_df['track_genre'].value_counts().head(20))

    st.subheader("📈 Correlation Heatmap")
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.heatmap(spotify_df[model_features].corr(), annot=False, cmap='coolwarm', ax=ax)
    st.pyplot(fig)

    st.subheader("🔍 Feature Histogram")
    feature = st.selectbox("Choose Feature", model_features)
    fig2, ax2 = plt.subplots()
    sns.histplot(spotify_df[feature], kde=True, ax=ax2, bins=30)
    st.pyplot(fig2)

# --------------------------------------
# 🧠 Model Evaluation and Comparison
# --------------------------------------
elif page == "Model Evaluation":
    st.title("🧠 Model Evaluation - Predicting Valence")
    models = {
        "Logistic Regression": LogisticRegression(max_iter=1000),
        "Random Forest": RandomForestClassifier(n_estimators=200),
        "SVM": SVC(probability=True),
        "KNN": KNeighborsClassifier(n_neighbors=5)
    }

    results = []
    fig, ax = plt.subplots(figsize=(8, 6))
    best_auc = 0
    best_model = None
    selected_model_name = ""

    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:, 1]

        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        auc = roc_auc_score(y_test, y_prob)
        results.append({"Model": name, "Accuracy": acc, "F1 Score": f1, "ROC AUC": auc})

        st.markdown(f"### 📌 {name} Performance")
        st.text(classification_report(y_test, y_pred))
        st.markdown(f"**Accuracy:** `{acc:.4f}` | **F1 Score:** `{f1:.4f}` | **ROC AUC:** `{auc:.4f}`")

        if auc > best_auc:
            best_auc = auc
            best_model = model
            selected_model_name = name

        fpr, tpr, _ = roc_curve(y_test, y_prob)
        ax.plot(fpr, tpr, label=f"{name} (AUC = {auc:.2f})")

    ax.plot([0, 1], [0, 1], linestyle='--', color='gray')
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.set_title("ROC Curve Comparison")
    ax.legend()
    st.pyplot(fig)

    results_df = pd.DataFrame(results).sort_values("ROC AUC", ascending=False)
    st.subheader("📊 Model Performance Summary")
    st.dataframe(results_df.style.format({"Accuracy": "{:.4f}", "F1 Score": "{:.4f}", "ROC AUC": "{:.4f}"}))

    st.success(f"✅ Best model selected for prediction: `{selected_model_name}`")
    best_model.fit(X_scaled, y_valence)
    st.session_state.best_model = best_model
    st.session_state.selected_model_name = selected_model_name

# --------------------------------------
# 🎵 ML-Based Recommendation (Optimized)
# --------------------------------------
elif page == "ML-Based Recommendation":
    st.title("🎵 ML-Based Mood Song Recommender")
    st.markdown("Upload your playlist, get mood predictions, and apply one filter (genre or mood).")

    if "best_model" not in st.session_state:
        st.warning("Please evaluate models first from the 'Model Evaluation' tab.")
    else:
        uploaded_file = st.file_uploader("📄 Upload your playlist JSON file", type="json")

        if uploaded_file:
            try:
                user_data = json.load(uploaded_file)
                user_df = pd.DataFrame(user_data)
                user_df = user_df.dropna(subset=model_features[:-1])
                user_scaled = scaler.transform(user_df[model_features[:-1]])
                predictions = st.session_state.best_model.predict(user_scaled)

                user_df['predicted_valence'] = predictions
                user_df['mood'] = user_df['predicted_valence'].apply(lambda x: 'Happy' if x == 1 else 'Calm')

                st.success(f"✅ Model used: `{st.session_state.selected_model_name}`")
                st.subheader("🎷 Mood Predictions")

                filter_option = st.selectbox("Filter By", ["None", "Genre", "Mood"])
                if filter_option == "Genre":
                    selected_genre = st.selectbox("Select Genre", user_df['track_genre'].dropna().unique())
                    user_df = user_df[user_df['track_genre'] == selected_genre]
                elif filter_option == "Mood":
                    selected_mood = st.radio("Select Mood", ["Happy", "Calm"])
                    user_df = user_df[user_df['mood'] == selected_mood]

                st.dataframe(user_df[['track_name', 'track_genre', 'valence', 'mood']], use_container_width=True)
            except Exception as e:
                st.error(f"Error processing uploaded file: {e}")

# --------------------------------------
# 🎷 Cosine Similarity Recommendation with PCA
# --------------------------------------
elif page == "Cosine Similarity Recommendation":
    st.title("🎷 Content-Based Song Recommendation with PCA")
    st.markdown("Upload your playlist and get similar songs using cosine similarity (with PCA).")

    uploaded_file = st.file_uploader("📄 Upload your playlist JSON file", type="json")

    if uploaded_file:
        try:
            user_data = json.load(uploaded_file)
            user_df = pd.DataFrame(user_data)
            user_df = user_df.dropna(subset=model_features[:-1])

            all_audio_data = spotify_df[model_features[:-1]].copy()
            all_scaled = scaler.transform(all_audio_data)
            user_scaled = scaler.transform(user_df[model_features[:-1]])

            pca = PCA(n_components=6)
            all_pca = pca.fit_transform(all_scaled)
            user_pca = pca.transform(user_scaled)

            spotify_sample = spotify_df.copy()
            spotify_sample['mood'] = spotify_sample['valence'].apply(lambda x: 'Happy' if x > 0.5 else 'Calm')

            sim_matrix = cosine_similarity(user_pca, all_pca)
            all_scores = sim_matrix.flatten()
            scores_df = pd.concat([spotify_sample] * len(user_df), ignore_index=True)
            scores_df['similarity_score'] = all_scores

            filter_option = st.selectbox("Filter By", ["None", "Genre", "Mood"])
            if filter_option == "Genre":
                selected_genre = st.selectbox("Select Genre", scores_df['track_genre'].dropna().unique())
                scores_df = scores_df[scores_df['track_genre'] == selected_genre]
            elif filter_option == "Mood":
                selected_mood = st.radio("Select Mood", ["Happy", "Calm"])
                scores_df = scores_df[scores_df['mood'] == selected_mood]

            top_n = st.slider("Number of songs to recommend", 3, 50, 10)
            final_recs = scores_df.sort_values("similarity_score", ascending=False).head(top_n)

            if final_recs.empty:
                st.warning("No songs match the selected filters.")
            else:
                st.subheader(f"🌟 Top {top_n} Recommended Songs")
                st.dataframe(final_recs[['track_name', 'track_genre', 'valence', 'mood', 'similarity_score']], use_container_width=True)

        except Exception as e:
            st.error(f"Error processing uploaded file: {e}")

